### ISSUE TITLE
Car mit Pfeiltasten bewegen 

### ISSUE THREAD

**Issue by oliadler** [Only-OGs/Python-Client#2]

**Comment by oliadler** [comment]
Ich habe mir erlaubt das Issue umzubenennen, denn prinzipiell haben wir auch die Bewegung des Autos (Sprite) erfolgreich umsetzen können, jedoch scheint es mir so als würde es da noch Optimierungsbedarf geben.

Das bezieht sich vorzugsweise auf die Keyevent-handling.

**Comment by araqs11** [comment]
Wurde implementiert im Ticket #10
