### ISSUE TITLE
Base-Kommunikation mit den Server implementieren

### ISSUE THREAD

**Issue by araqs11** [Only-OGs/Python-Client#4]

**Comment by araqs11** [comment]
Also die Idee ist es, Funktionen wie client.send_data(data) und client.receive_data() zu haben welche einen das handeln mit data erleichtern sollten.

Ich schau mir das mal über das Wochenende an ob das möglich ist, denkt ihr das wäre eine gute idee? @oliadler @PhilC137 @Pascal378

**Comment by Pascal378** [comment]
Diese Funktionen waren in der Theorie bereits implementiert und wurden hier entfernt: https://github.com/Only-OGs/Python-Client/commit/f91c6d0b10c6ab82ffe25e4cd32a862754282d03

Über die emit funktion die in dem commit entfernt wurde, werden daten an den Server gegeben, da würde man quasi die Fahrzeugposition übergeben in der Gameloop.

Der Server hat eine Response Funktion, in dieser würde er dann die Koordinaten aller anderen Wagen zurück an den Spieler senden.

Wichtig zu wissen wäre wie ich bereits gestern sagte: 
Welche Daten werden gebraucht um die Position eines Objekts zu bestimmten auf allen Clients, das wollte ich dann ja entsprechend bewerkstelligen dann per Code im Server. Die Aufgabe der Clients wäre dann nur in einer Game Loop jedem Objekt seine neue Position zu weisen nach dem die neuen Positionen vom Server zurück kommen

**Comment by araqs11** [comment]
Ja ich denke wir können das Issue erstmal ruhen lassen und später aufgreifen wenn wir das Spiel fertig haben oder zumindest soweit sind das wir wissen welche data genau wir senden/brauchen

**Comment by oliadler** [comment]
Werde mich damit auseinandersetzen, da ich sowieso schon die client.py File begonnen hatte.
Ich spreche mich mit dem java Team ab, zwecks wie JSON Objekte und wie konkret diese aufgebaut sind. Da wir diese Art nutzen wollen um den Datenaustausch mit dem Server zu garantieren. @araqs11

**Comment by oliadler** [comment]
Die Base-Kommunkation steht jetzt soweit. Der Client kann jetzt mit dem Server kommunizieren. Als nächstes steht die Registrierung und das Login an.

**Comment by Pascal378** [comment]
> Die Base-Kommunkation steht jetzt soweit. Der Client kann jetzt mit dem Server kommunizieren. Als nächstes steht die Registrierung und das Login an.

Wenn irgendwie Hilfe benötigt wird meld dich

**Comment by oliadler** [comment]
Nachtrag: Regsitrierung und Login läuft, auch das Beitreten in eine Lobby oder das Erstellen einer Lobby.
Auch das Empfangen der Strecke vom Server funktioniert.
