### ISSUE TITLE
Code Struktur, Aufteilung etc.

### ISSUE THREAD

**Issue by PhilC137** [Only-OGs/Python-Client#6]
Wie wollen wir den Code aufteilen? 
Sollen wir wie im PM Dungeon viele unter Klassen anlegen oder eher wie das Vorbild in wenigen Dateien.

**Comment by araqs11** [comment]
Erstmal in wenigen Dateien würd ich sagen, wir können später wenn wir fertig sind uns überlegen, wie man das genau aufteilt
