### ISSUE TITLE
Main Menü für den Python Client

### ISSUE THREAD

**Issue by araqs11** [Only-OGs/Python-Client#7]
Idee ist, dass man einen Main Menü screen wo man die folgendes auswählen kann:

-  Join a Lobby with a Code
-  Browse for a Lobby
-  setting or so

sollte glaube ich erst nach dem eigentlich game implementiert werden denke ich, kann man aber auch vorziehen wenn wir merken das jemand sonst leer lauf hat

**Comment by araqs11** [comment]
Hab es Philipp zugeordnet, da er es machen möchte.

**Comment by araqs11** [comment]
Bitte noch so implementieren, dass die Font direkt mitgeliefert wird, danke

**Comment by oliadler** [comment]
Hallo zusammen, 
aktuell habe ich mich damit beschäftigt unser Menü zu optimieren, primär was die Buttons und die dazugehörigen Keyevents angeht. Ich war erfreut zu sehen, dass es auch eine pyglet.gui Bibliothek gibt mit Pushbuttons, aber leider lassen sich dort keine Texte für den Buttoninhalt übergeben. Daher beschloss ich auch hier einen Workaround zu suchen: Eigene TextPushButton klasse, die jedoch von Pushbutton erbt. Die TextPushButtonklasse wird jedoch um den Initialiserungsparameter Text erweitert. Aber auch hier gab dann erneute Probleme mit den superparameter der parentklasse Pushbutton. 
Gerne würde ich daher mich in pygame ausprobieren, da auch der Einstieg laut Foren und anderen Internetseiten einfacher ist als in pyglet. Gerne können wir die Tage nochmal darüber sprechen, da es in einem Projekt diesen Ausmaßen normal ist auf Hindernisse oder Schwierigkeiten zu stoßen.
Jedoch habe ich bereits mit @PhilC137 darüber gesprochen und er ist nicht tendenziell auch dafür.
Was sagt Ihr dazu @Pascal378 @araqs11 ?

Grüße
Olli

**Comment by Pascal378** [comment]
Ich kümmer mich ohnehin mehr um Server und bin ja eher Ansprechpartner für solche Funktionen mittlerweile (wenn auch ich euch natürlich immernoch hier und da unterstützen kann wenn ihr Probleme habt) und würde mich da deshalb einfach mal der Wahl entziehen da ihr mehr mit dem Framework konfrontiert seid als ich. Für mich ist da alles Recht

**Comment by PhilC137** [comment]
Ich habe mich die letzten Stunden mit Pygame befasst und denke, dass es Sinnvoll wäre die Library zu wechseln, da zu dieser Library viel mehr Input im Netz existiert.

**Comment by araqs11** [comment]
LGTM
