### ISSUE TITLE
Grundspiel programmieren in Python

### ISSUE THREAD

**Issue by araqs11** [Only-OGs/Python-Client#8]
Damit wir die Arbeit besser verteilen können würde ich gerne das ein grundlegendes Spiel implementieren.

Dies wäre das ein Auto und eine Straße gerendert wird, und man die Straße befahren kann nach links und rechts.

Ich denke ich werde mich an dem [Tutorial](https://codeincomplete.com/articles/javascript-racer-v1-straight/) halten. 

Falls ich noch irgendwas vergessen habe am besten hier drunter schreiben, danke

**Comment by araqs11** [comment]
Hab mich beim Auto sehr an dem von @oliadler gehalten, war sehr gut schon umgesetzt, hab es eigentlich nur überarbeitet. 
Kann ich dann die car.py die im Hauptordner liegt löschen?

**Comment by oliadler** [comment]
Ja kannst du löschen. Ich habe das ganze ja sowieso noch mal lokal liegen, falls ich doch darauf zurückgreifen muss.

**Comment by araqs11** [comment]
Hab das Grundspiel soweit ich konnte implementiert, was noch fehlt ist der Hintergrund, das Auto und evnt paar andere Straßen farben. Ich mache dafür mal drafts bereit sodas jeder sich das als Ticket holen kann wenn er das machen will.
